/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_prenzl_stdrules_JNIComputation */

#ifndef _Included_net_sf_prenzl_stdrules_JNIComputation
#define _Included_net_sf_prenzl_stdrules_JNIComputation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_prenzl_stdrules_JNIComputation
 * Method:    compute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_prenzl_stdrules_JNIComputation_compute
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_prenzl_stdrules_JNIComputation
 * Method:    getCurrent
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_sf_prenzl_stdrules_JNIComputation_getCurrent
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_sf_prenzl_stdrules_JNIComputation
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_prenzl_stdrules_JNIComputation_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
